---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-williamzhang-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi
